pocketbase_url = "https://jasnowidzdb.yehor.pl.eu.org" # must be a valid pocketbase url with created collections
collections = [ # with every new script that accesses pocketbase new entries must be added
  "test",
  "lubeu_events",
  "lubeu_running",
  "zoom",
  "zoom_running",
  "labirynt_wystawy",
  "labirynt_wydarzenia",
  "events" # mono-collection with all unique events
]

[scrapers] # scrapers.script_id

[scrapers.lublineu]
enabled = true
output = "lublineu_events.json"

[scrapers.lublineu_running]
enabled = true
output = "lublin_eu_running.json"

[scrapers.zoom]
enabled = true
output = "zoom_events.json"

[scrapers.zoom_running]
enabled = true
output = "zoom_events_running.json"

[scrapers.labirynt_exhibitions]
enabled = true
output = "labirynt_exhibitions.json"

[scrapers.labirynt_events]
enabled = true
output = "labirynt_events.json"
