[project]
name = "jasnowidzpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "colorama>=0.4.6",
    "dotenv>=0.9.9",
    "pocketbase>=0.17.3",
    "requests>=2.34.2",
    "tqdm>=4.68.2",
]

[tool.pyright]
typeCheckingMode = "standard"
